import type { Metadata } from "next";
import { Inter, Space_Grotesk, Source_Sans_3 } from "next/font/google";

import "./globals.css";
import Header from "@/components/header";
import { Providers } from "@/providers";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

const spaceGrotesk = Space_Grotesk({ 
  subsets: ["latin"] 
})

const sans3 = Source_Sans_3({ 
  subsets: ["latin"] 
})

export const metadata: Metadata = {
  title: "Usmaila Abdoul | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(spaceGrotesk.className, inter.className)}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
