import { Home } from "@/components/home/Home";
import { Metadata } from "next";

export function generateMetadata(): Metadata {
  return {
    title: "Usmaila Abdoul | Software Engineer",
    description: "Generated by create next app",
  };
}

export default function HomePage() {
  return (
    <Home />
  );
}
